apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  labels:
    type: clusterip
spec:
  type: ClusterIP
  selector:
    deployment-name: {{.DeploymentName}}
  ports:
  - port: 8080
    targetPort: 80
