apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    group: for-clusterip
spec:
  replicas: {{.NumReplicas}}
  selector:
    matchLabels:
      name: {{.Name}}
  template:
    metadata:
      labels:
        group: ilb-load
        name: {{.Name}}
        deployment-name: {{.DeploymentName}}
    spec:
      containers:
      - name: {{.Name}}
        image: nginx
        ports:
        - containerPort: 8080
